using System.Collections;
using System.Reflection;
using System.Text;
using Glorp.Api.Glorpiatr;

namespace Glorp.Api.Generator;

public static class ClientGenerator
{
    public static string AutoGenHeader() => $"""
        // <auto-generated>
        // Generated by Glorp.Api TypeScriptGenerator on {DateTime.UtcNow}.
        // Do not edit by hand. Regenerate: run api project with "generate-client".
        // </auto-generated>

        """;

    public static void Generate()
    {
        WriteIfChanged("frontend/src/glorp/types.ts", GenerateTypes());
        WriteIfChanged("frontend/src/glorp/client.ts", GenerateClient());
    }

    private static void WriteIfChanged(string filePath, string newContent)
    {
        var solutionDir = TryGetSolutionDirectoryInfo();
        var rootDir = Path.Combine(solutionDir?.FullName ?? Directory.GetCurrentDirectory(), "..");

        var outputPath = Path.Combine(rootDir, filePath);
        var outputDir = Directory.GetParent(outputPath)!.FullName;

        Directory.CreateDirectory(outputDir);

        if (File.Exists(outputPath))
        {
            var existing = File.ReadAllText(outputPath);
            if (StripAutoGenHeader(existing) == StripAutoGenHeader(newContent))
            {
                Console.WriteLine($"- {filePath} is up to date, skipping.");
                return;
            }
        }

        File.WriteAllText(outputPath, newContent);

        var byteCount = Encoding.UTF8.GetByteCount(newContent);
        Console.WriteLine($"- Wrote {byteCount} bytes to {filePath}");
    }

    private static string StripAutoGenHeader(string content)
    {
        const string endMarker = "// </auto-generated>";
        if (!content.StartsWith("// <auto-generated>", StringComparison.Ordinal))
            return content;

        var idx = content.IndexOf(endMarker, StringComparison.Ordinal);
        if (idx < 0) return content;

        return content[(idx + endMarker.Length)..];
    }

    public static string GenerateTypes()
    {
        var asm = Assembly.GetExecutingAssembly();
        var docs = XmlDocs.LoadFor(asm);
        var allTypes = asm.GetTypes()
            .Where(t => !t.IsAbstract && !t.IsInterface && !t.IsGenericTypeDefinition)
            .ToArray();

        var requests = allTypes.Where(t => ImplementsGeneric(t, typeof(IGlorpRequest<>))).ToArray();
        var responses = allTypes.Where(t => ImplementsGeneric(t, typeof(IGlorpResponse<>))).ToArray();

        // Collect all referenced data types transitively.
        var emitted = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var dataTypes = new HashSet<Type>();

        foreach (var r in responses)
        {
            var dataType = r.GetInterfaces()
                .First(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IGlorpResponse<>))
                .GetGenericArguments()[0];

            CollectReferencedTypes(dataType, dataTypes);
        }

        foreach (var req in requests)
        {
            foreach (var p in req.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                CollectReferencedTypes(p.PropertyType, dataTypes);
        }

        foreach (var t in dataTypes)
        {
            emitted[t.Name] = EmitDataInterface(t, docs);
        }

        foreach (var req in requests)
        {
            emitted[req.Name] = EmitRequest(req, docs);
        }

        foreach (var resp in responses)
        {
            emitted[resp.Name] = EmitResponse(resp, docs);
        }

        var requestNames = requests.Select(r => r.Name).OrderBy(n => n, StringComparer.Ordinal).ToArray();
        var responseNames = responses.Select(r => r.Name).OrderBy(n => n, StringComparer.Ordinal).ToArray();

        // Map each request to its declared response type via IGlorpRequest<TResponse>.
        var requestToResponse = requests
            .Select(r => (
                Request: r.Name,
                Response: r.GetInterfaces()
                    .First(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IGlorpRequest<>))
                    .GetGenericArguments()[0].Name))
            .OrderBy(p => p.Request, StringComparer.Ordinal)
            .ToArray();

        var types = new StringBuilder();
        types.Append(AutoGenHeader());
        types.AppendLine();
        foreach (var (_, body) in emitted)
        {
            types.AppendLine(body);
        }

        types.AppendLine($"export type GlorpRequest = {(requestNames.Length == 0 ? "never" : string.Join(" | ", requestNames))};");
        types.AppendLine($"export type GlorpResponse = {(responseNames.Length == 0 ? "never" : string.Join(" | ", responseNames))};");
        types.AppendLine();
        types.AppendLine("export interface GlorpRequestResponseMap {");
        foreach (var (req, resp) in requestToResponse)
        {
            types.AppendLine($"  {req}: {resp};");
        }
        types.AppendLine("}");
        types.AppendLine();
        types.AppendLine("export type GlorpResponseFor<TReq extends GlorpRequest> =");
        types.AppendLine("  TReq[\"$type\"] extends keyof GlorpRequestResponseMap");
        types.AppendLine("    ? GlorpRequestResponseMap[TReq[\"$type\"]]");
        types.AppendLine("    : never;");

        return types.ToString();
    }

    public static string GenerateClient()
    {
        var client = new StringBuilder();

        client.Append(AutoGenHeader());
        client.AppendLine();

        client.Append("""
        import type { GlorpRequest, GlorpResponseFor } from "./types";

        export interface GlorpClientOptions {
          baseUrl?: string;
          path?: string;
          fetch?: typeof fetch;
          headers?: HeadersInit;
        }

        export class GlorpError extends Error {
          readonly status: number;
          readonly body: string;

          constructor(status: number, body: string) {
            super(`Glorp request failed (${status}): ${body}`);
            this.name = "GlorpError";
            this.status = status;
            this.body = body;
          }
        }

        /**
         * A client for sending GlorpRequests to a Glorp server and receiving responses.
         * The client can be configured with a base URL, path, custom fetch implementation, and default headers.
         * Use the `send` method to send a GlorpRequest and receive the corresponding response.
         */
        export class GlorpClient {
          private readonly baseUrl: string;
          private readonly path: string;
          private readonly fetchImpl: typeof fetch;
          private readonly headers: HeadersInit;

          constructor(options: GlorpClientOptions = {}) {
            this.baseUrl = (options.baseUrl ?? "").replace(/\/+$/, "");
            this.path = options.path ?? "/glorp";
            this.fetchImpl = options.fetch ?? fetch.bind(globalThis);
            this.headers = options.headers ?? {};
          }

          /**
            * Sends a GlorpRequest to the server and returns the corresponding response.
            * @param request - The GlorpRequest to send.
            * @param init - Optional settings for the request, such as an AbortSignal.
            * @returns A promise that resolves to the response corresponding to the request.
            * @throws GlorpError if the response status is not OK (200-299).
            */
          async send<TReq extends GlorpRequest>(
            request: TReq,
            init?: { signal?: AbortSignal },
          ): Promise<GlorpResponseFor<TReq>> {
            const response = await this.fetchImpl(`${this.baseUrl}${this.path}`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                Accept: "application/json",
                ...this.headers,
              },
              body: JSON.stringify(request),
              signal: init?.signal,
            });

            if (!response.ok) {
              throw new GlorpError(response.status, await response.text());
            }

            return (await response.json()) as GlorpResponseFor<TReq>;
          }
        }
        """);

        return client.ToString();
    }

    private static string EmitRequest(Type requestType, XmlDocs docs)
    {
        var sb = new StringBuilder();
        sb.Append(JsDoc(docs.GetTypeSummary(requestType), indent: ""));
        sb.AppendLine($"export interface {requestType.Name} {{");
        sb.AppendLine($"  $type: \"{requestType.Name}\";");
        foreach (var p in requestType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            EmitProperty(sb, p, docs);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitResponse(Type responseType, XmlDocs docs)
    {
        var dataType = responseType.GetInterfaces()
            .First(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IGlorpResponse<>))
            .GetGenericArguments()[0];

        var sb = new StringBuilder();
        sb.Append(JsDoc(docs.GetTypeSummary(responseType), indent: ""));
        sb.AppendLine($"export interface {responseType.Name} {{");
        sb.AppendLine($"  $type: \"{responseType.Name}\";");
        sb.AppendLine($"  success: boolean;");
        sb.AppendLine($"  message?: string | null;");
        sb.AppendLine($"  data?: {ToTs(dataType)} | null;");

        // Emit any additional properties not part of the base IGlorpResponse contract.
        var baseProps = new HashSet<string>(StringComparer.Ordinal) { "Data", "Success", "Message" };
        foreach (var p in responseType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (baseProps.Contains(p.Name)) continue;
            EmitProperty(sb, p, docs);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitDataInterface(Type type, XmlDocs docs)
    {
        var sb = new StringBuilder();
        sb.Append(JsDoc(docs.GetTypeSummary(type), indent: ""));
        sb.AppendLine($"export interface {type.Name} {{");
        foreach (var p in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            EmitProperty(sb, p, docs);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitProperty(StringBuilder sb, PropertyInfo property, XmlDocs docs)
    {
        var (tsType, optional) = ToTsWithOptional(property.PropertyType, property);

        var name = ToCamel(property.Name);
        sb.Append(JsDoc(docs.GetPropertySummary(property.DeclaringType!, property.Name), indent: "  "));
        sb.AppendLine($"  {name}{(optional ? "?" : "")}: {tsType};");
    }

    private static string JsDoc(string? summary, string indent)
    {
        if (string.IsNullOrWhiteSpace(summary)) return string.Empty;
        var sb = new StringBuilder();
        sb.Append(indent).AppendLine("/**");
        foreach (var line in summary.Replace("\r\n", "\n").Split('\n'))
        {
            sb.Append(indent).Append(" * ").AppendLine(line);
        }
        sb.Append(indent).AppendLine(" */");
        return sb.ToString();
    }

    private static (string tsType, bool optional) ToTsWithOptional(Type type, PropertyInfo prop)
    {
        var nullableCtx = new NullabilityInfoContext().Create(prop);
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null)
        {
            return ($"{ToTs(underlying)} | null", true);
        }
        if (nullableCtx.ReadState == NullabilityState.Nullable && !type.IsValueType)
        {
            return ($"{ToTs(type)} | null", true);
        }
        return (ToTs(type), false);
    }

    private static string ToTs(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);

        if (underlying is not null)
            return ToTs(underlying);

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan))
            return "string";

        if (type == typeof(bool)) return "boolean";

        if (type == typeof(byte) || type == typeof(sbyte) || type == typeof(short) || type == typeof(ushort)
            || type == typeof(int) || type == typeof(uint) || type == typeof(long) || type == typeof(ulong)
            || type == typeof(float) || type == typeof(double) || type == typeof(decimal))
            return "number";

        if (type == typeof(object)) return "unknown";

        if (type.IsArray)
            return ToTs(type.GetElementType()!) + "[]";

        if (type.IsGenericType)
        {
            var def = type.GetGenericTypeDefinition();
            var args = type.GetGenericArguments();
            if (def == typeof(IEnumerable<>) || def == typeof(List<>) || def == typeof(IList<>)
                || def == typeof(ICollection<>) || def == typeof(IReadOnlyList<>) || def == typeof(IReadOnlyCollection<>)
                || def == typeof(HashSet<>) || def == typeof(ISet<>))
                return ToTs(args[0]) + "[]";

            if (def == typeof(Dictionary<,>) || def == typeof(IDictionary<,>) || def == typeof(IReadOnlyDictionary<,>))
            {
                var keyTs = ToTs(args[0]) == "number" ? "number" : "string";
                return $"Record<{keyTs}, {ToTs(args[1])}>";
            }
        }

        if (typeof(IEnumerable).IsAssignableFrom(type) && type != typeof(string))
        {
            var iface = type.GetInterfaces().FirstOrDefault(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));
            if (iface is not null)
                return ToTs(iface.GetGenericArguments()[0]) + "[]";
        }

        // Fall back to the type name (it should be emitted as an interface).
        return type.Name;
    }

    private static void CollectReferencedTypes(Type type, HashSet<Type> sink)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null) { CollectReferencedTypes(underlying, sink); return; }

        if (type.IsArray) { CollectReferencedTypes(type.GetElementType()!, sink); return; }

        if (type.IsGenericType)
        {
            foreach (var a in type.GetGenericArguments()) CollectReferencedTypes(a, sink);
            return;
        }

        if (IsPrimitiveOrBuiltin(type)) return;
        if (type.Namespace?.StartsWith("System", StringComparison.Ordinal) == true) return;
        if (!sink.Add(type)) return;

        foreach (var p in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            CollectReferencedTypes(p.PropertyType, sink);
    }

    private static bool IsPrimitiveOrBuiltin(Type type) =>
        type.IsPrimitive || type == typeof(string) || type == typeof(decimal) || type == typeof(Guid)
        || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan) || type == typeof(object);

    private static bool ImplementsGeneric(Type type, Type genericInterface) =>
        type.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == genericInterface);

    private static string ToCamel(string name) =>
        string.IsNullOrEmpty(name) || char.IsLower(name[0]) ? name : char.ToLowerInvariant(name[0]) + name[1..];

    

    public static DirectoryInfo? TryGetSolutionDirectoryInfo()
    {
        DirectoryInfo? directory = new(Directory.GetCurrentDirectory());
        while (directory != null && directory.GetFiles("*.slnx").Length == 0)
        {
            directory = directory.Parent;
        }
        return directory;
    }
}
