// <auto-generated>
// Generated by Glorp.Api TypeScriptGenerator on 27/05/2026 10:54:53.
// Do not edit by hand. Regenerate: run api project with "generate-client".
// </auto-generated>

import type { GlorpRequest, GlorpResponseFor } from "./types";

export interface GlorpClientOptions {
  baseUrl?: string;
  path?: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
}

export class GlorpError extends Error {
  readonly status: number;
  readonly body: string;

  constructor(status: number, body: string) {
    super(`Glorp request failed (${status}): ${body}`);
    this.name = "GlorpError";
    this.status = status;
    this.body = body;
  }
}

/**
 * A client for sending GlorpRequests to a Glorp server and receiving responses.
 * The client can be configured with a base URL, path, custom fetch implementation, and default headers.
 * Use the `send` method to send a GlorpRequest and receive the corresponding response.
 */
export class GlorpClient {
  private readonly baseUrl: string;
  private readonly path: string;
  private readonly fetchImpl: typeof fetch;
  private readonly headers: HeadersInit;

  constructor(options: GlorpClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? "").replace(/\/+$/, "");
    this.path = options.path ?? "/glorp";
    this.fetchImpl = options.fetch ?? fetch.bind(globalThis);
    this.headers = options.headers ?? {};
  }

  /**
    * Sends a GlorpRequest to the server and returns the corresponding response.
    * @param request - The GlorpRequest to send.
    * @param init - Optional settings for the request, such as an AbortSignal.
    * @returns A promise that resolves to the response corresponding to the request.
    * @throws GlorpError if the response status is not OK (200-299).
    */
  async send<TReq extends GlorpRequest>(
    request: TReq,
    init?: { signal?: AbortSignal },
  ): Promise<GlorpResponseFor<TReq>> {
    const response = await this.fetchImpl(`${this.baseUrl}${this.path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        ...this.headers,
      },
      body: JSON.stringify(request),
      signal: init?.signal,
    });

    if (!response.ok) {
      throw new GlorpError(response.status, await response.text());
    }

    return (await response.json()) as GlorpResponseFor<TReq>;
  }
}