// <auto-generated>
// Generated by Glorp.Api TypeScriptGenerator on 27/05/2026 10:54:53.
// Do not edit by hand. Regenerate: run api project with "generate-client".
// </auto-generated>

/**
 * A Bar
 */
export interface Bar {
  name: string;
  height: number;
  weight: number;
}

/**
 * A Foo
 */
export interface Foo {
  name: string;
  color: string;
}

/**
 * A Glorp Bars request object, returns any Bar with a height greater than or equal to the provided MinHeight
 */
export interface GetBarsRequest {
  $type: "GetBarsRequest";
  minHeight: number;
}

/**
 * A Glorp Bars response object
 */
export interface GetBarsResponse {
  $type: "GetBarsResponse";
  success: boolean;
  message?: string | null;
  data?: Bar[] | null;
}

/**
 * A Glorp Foos request object, returns any Foo with a name that contains the provided Name string (case-insensitive)
 */
export interface GetFoosRequest {
  $type: "GetFoosRequest";
  name: string;
}

/**
 * A Glorp Foos response object
 */
export interface GetFoosResponse {
  $type: "GetFoosResponse";
  success: boolean;
  message?: string | null;
  data?: Foo[] | null;
}

export type GlorpRequest = GetBarsRequest | GetFoosRequest;
export type GlorpResponse = GetBarsResponse | GetFoosResponse;

export interface GlorpRequestResponseMap {
  GetBarsRequest: GetBarsResponse;
  GetFoosRequest: GetFoosResponse;
}

export type GlorpResponseFor<TReq extends GlorpRequest> =
  TReq["$type"] extends keyof GlorpRequestResponseMap
    ? GlorpRequestResponseMap[TReq["$type"]]
    : never;
